### ISSUE TITLE
Fix css compatibility for older browsers

### ISSUE THREAD

**Issue by ismay** [ismay/ismaywolff.nl#1002]
For:

```css
body {
  font-family: var(--font-family);
  cursor: zoom-in;
  display: flex;
  pointer-events: none;
  position: fixed;
  transition: background 300ms;
  width: calc(2 / 3 * 100%);
  transform: scale(0.7);
  transform: translate3d(10px, 0, 0px);
}
```
